### ISSUE TITLE
关于3MDAD数据集深度图像的问题

### ISSUE THREAD

**Issue by congduan-HNU** [kevinsu628/3MDAD#1]
您好，感谢您提供的3MDAD数据集修复代码。我也从数据集网站下载了这个数据集，我发现深度图像似乎没有数据，虽然它占用了很大的空间，但是里面像素位数据几乎都是0，请问您是否也有这个问题？

**Comment by kevinsu628** [comment]
Hi, the depth images are in 16 bits so you need some normalization in order to “see” it. I included that part in the code. 
(written this in English so if other people see this they can understand as well)

**Comment by congduan-HNU** [comment]
Thank you, I have used the code you provided to get a visual depth image, I will look at your code in detail.

**Comment by MachineLearning11** [comment]
> 您好，感谢您提供图像的 3MDAD 集。我也从网站下载了这个数据集，我发现里面似乎没有数据，虽然它占用了很大的空间，但是里面的数据集位数据几乎都是0，请问您是否也有这个问题？

你好，你是如何下载下载的该数据集，是给作者发的邮件吗，我给他邮件没有得到回复，如果看到了希望可以回复！谢谢
